### ISSUE TITLE
Webpack compilation is not compatible

### ISSUE THREAD

**Issue by bigomega** [jonschlinkert/assign-deep#1]
When using webpack to package the files, libraries, it converts every `require` to a function.
So,

``` javascript
var lazy = require('lazy-cache')(require);
lazy('is-extendable', 'isObject');
```

is converted to 

``` javascript
var lazy = __webpack_require__(385)(__webpack_require__(386));
```

where it says no arguments passed to the last require and hence breaks with an error

``` javascript
"lazy-cache Cannot find module 'is-extandable' ./index.js"
```

**Comment by jonschlinkert** [comment]
thanks, we just talked about this. we're going to update all packages that use lazy-cache and browserify to have a special browserify build. sorry for the issue

**Comment by tunnckoCore** [comment]
@jonschlinkert It looks like if `var require = require('lazy-cache')(require)` it would works, i think?

As for browserify works.

**foo.js**

``` js
var require = require('lazy-cache')(require)
var last = require('get-last-value')

console.log(last()({foo: 'bar', a: {foo: 'qux'}}, 'foo')) //=> 'qux'
```

**index.html**

``` html
<h1>Open up the console</h1>
<script src="./bundle.js"></script>
```

**browserify**

```
browserify foo.js -o bundle.js
```

~~edit: i'll try in a bit.~~ damn not works, lol, okey.

**Comment by jonschlinkert** [comment]
just to throw ideas out, what we're thinking of doing is something like this:

Keep lazy-cached requires in a single, specific file, say `utils.js`, so they can be used in the lib with:

``` js
var utils = require('./utils');
utils.assign(a, b);
```

We would also then have a browserify-compatible companion file with the same deps, but not lazy-cached, and we would tell browserify to use that file as `utils.js` 

thoughts?

**Comment by tunnckoCore** [comment]
> Keep lazy-cached requires in a single, specific file, say utils.js

I think it won't work. Actually, tried it over `glob-object/example.js`, not work.

**Comment by tunnckoCore** [comment]
@jonathanong any ideas?

**Comment by jonschlinkert** [comment]
I thought of a rather elegant solution, if anyone can think of downsides let me know.

Basically we just need to trick browserify and webpack into recognizing the require definitions by temporarily re-assigning require.

``` js
var lazy = module.exports = require('lazy-cache')(require);
var fn = require;
require = lazy;
require('foo'); // `require` here is actually `lazy-cache`
require = fn;
```

This seems to work okay. I have no idea how durable of a solution this is. If it does in fact work, one more benefit is that we can still use the custom variable feature of lazy-cache:

``` js
var lazy = module.exports = require('lazy-cache')(require);
var fn = require;
require = lazy;
require('foo', 'bar'); // `bar` is ignored by browserify, but still works with lazy-cache
require = fn;
```

**Comment by tunnckoCore** [comment]
Actually I tried something like that then and it didn't work completely, but this seems to work. I just didn't mind to restore the original require like that `require = fn;`, huh. Good job!

**Comment by jonschlinkert** [comment]
thanks!

**Comment by jonschlinkert** [comment]
btw, the other awesome thing about this is that after the code is browserified, the code is still "lazy". it doesn't provide as much of an advantage when all the code is in one file, but still... pretty nice

**Comment by doowb** [comment]
@bigomega we just released [unlazy cache](https://www.npmjs.com/package/unlazy-loader) that you can use in your webpack build to allow using modules that use `lazy-cache` (like this one).

I'm going to close this now, but please feel free to reopen if you're still running into issues.
