### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by rightaway** [jonschlinkert/assign-deep#15]
A changelog would be useful either as a file in the repo or as notes in the releases section of github.

For example I can't tell what has changed between 0.4.7 and 1.0.0 and if I should upgrade. What has changed in the 1.0.0 release, any breaking changes or differences in how it works?

**Comment by jonschlinkert** [comment]
Done! GitHub actually provides a wonderful and detailed changelog that works great for micro-libraries like this one https://github.com/jonschlinkert/assign-deep/commits/master.
