### ISSUE TITLE
Breaks on arrays

### ISSUE THREAD

**Issue by ghost** [jonschlinkert/assign-deep#16]
```js
assign({ a: [1] }, { a: [2] }); // => { a: [2] }
```

I was expecting `a` to be the combination of both arrays, but instead it is the value of the latter object.

**Comment by ghost** [comment]
My webpack config broke because I use this for extending the base configuration.

**Comment by ghost** [comment]
@jonschlinkert Do you have anything to contribute to this?

**Comment by jonschlinkert** [comment]
You didn’t clearly state the problem. What is the value in your example, the expected or unexpected result. Also, that looks correct, there is a reason assign is being used instead of merge.

**Comment by ghost** [comment]
@jonschlinkert Fixed.

**Comment by jonschlinkert** [comment]
This behavior would be unexpected for all users, since assign never merges arrays, only “union” or deep merge typically do that.

**Comment by ghost** [comment]
You *should* highlight this in the README

**Comment by jonschlinkert** [comment]
You should do a pull request. You are the first person who has had this expectation.
