### ISSUE TITLE
crashes on this object

### ISSUE THREAD

**Issue by despairblue** [jonschlinkert/assign-deep#3]
``` js
const deepAssign = require('assign-deep')

const a = {
  b: {}
}

a.b = a

console.log(deepAssign({}, a))
```

**Comment by jonschlinkert** [comment]
actually isn't this expected? Or should this scrub circular references first? Seems like that is outside the scope of this lib but I'm open to feedback

**Comment by despairblue** [comment]
I think an error similar `JSON.stringy(a)` gives would be easier to track down for anyone stumbling upon this:

```
[TypeError: Converting circular structure to JSON]
```

**Comment by jonschlinkert** [comment]
closing since I think this library does what is intended
