### ISSUE TITLE
Difference between this and mixin-deep?

### ISSUE THREAD

**Issue by rightaway** [jonschlinkert/assign-deep#4]
I've tested a few use cases against `assign-deep` and another project of yours `mixin-deep`, and they both seem to do what I want.

- Recursive
- Don't merge arrays but overwrites them with the last array found for a property
- Overwrite keys with `null` and `undefined` rather than ignoring them
- Don't make any changes to `object1` and `object2` when an empty object `{}` passed as first argument (e.g. `assign({}, object1, object2)` and `mixin({}, object1, object2)`)

How are these 2 projects different, can you give some use cases with inputs that produce different outputs? Just want to make sure I'm using the right package for when I have to deal with more complex object structures where things may behave differently.

**Comment by jonschlinkert** [comment]
Hi @rightaway, thanks for creating the issue. 

assign-deep only assigns enumerable properties (equivalent of `for own`), mixin-deep doesn't care if they're enumerable or not (equivalent of `for in`).  Also assign-deep should work with es6 symbol properties as well, mixin-deep does not.

**Comment by rightaway** [comment]
By `for own` do you mean `for of`, as in the loop? (Not sure what `for own` is.)

Also I though `for in` loops only loop through enumerable properties? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in

**Comment by jonschlinkert** [comment]
I meant `forOwn` used in utilities like lodash or https://www.npmjs.com/package/for-own. Short for:

```js
for (var key in obj) {
  if (obj.hasOwnProperty(key)) {
    // do stuff
  }
}
```

> Also I though for in loops only loop through enumerable properties?

I was saying that assign-deep only merges "own" and "enumerable"  properties.

**Comment by jonschlinkert** [comment]
closing since this isn't a bug or feature request

**Comment by rightaway** [comment]
Just came across `merge-deep` as well, how does `assign-deep` differ from it? I tried them both against a few cases and they seem to output the same results.

**Comment by jonschlinkert** [comment]
@rightaway the projects all describe their differences. My answer above was information from the readmes of those projects.
