### ISSUE TITLE
Throw error when string or number passed accidentally?

### ISSUE THREAD

**Issue by rightaway** [jonschlinkert/assign-deep#5]
Would it make sense for assign-deep to throw an error when a string or number is passed?

```js
const element = 'string'
console.log(assignDeep({a: 1}, element, {b: 2, a: 999}))
```

This prints `{ a: 999, b: 2 }`, as expected. But for someone who passed in the string, it's almost certainly an error in their code because they wouldn't be passing a string or number in the first place. It would be helpful to get an error right away.

**Comment by jonschlinkert** [comment]
I'm not sure, I don't think this should cause an error. 

IMHO, there are scenarios where a string or other primitive value might intentionally be overridden by an object. Like when options allow either an object or string to be defined as the value. the default might be a string and if the user defines an object, you might simply want to merge the object over in place of the string value.

**Comment by doowb** [comment]
I agree that this shouldn't throw an error and that it's better to check the arguments before passing into `assignDeep` if it's necessary to ensure that everything is an object.
