### ISSUE TITLE
Shouldn't assign-deep mutate dates?

### ISSUE THREAD

**Issue by nikitaeverywhere** [jonschlinkert/assign-deep#7]
Hello! Thanks for the useful library.

Recently I've noticed that it does mutate Dates:

```javascript
var assignDeep = require("assign-deep");

const a = {
    date: new Date(),
    anyObj: {}
};

const b = assignDeep({}, a);

console.log(
    a.anyObj === b.anyObj, // Gives false as expected.
    a.date === b.date // Gives true. Should it be false?
); 
```

My idea is that date objects must not be mutated as well as any other objects. Not to be unfounded, `a.date.setTime(X)` will change both `a.date` and `b.date` in the example above. What do you think? I can process with the pull request if you agree.

Thank you!

**Comment by jonschlinkert** [comment]
> What do you think? I can process with the pull request if you agree.

I agree we should support what you expected, but I think a better approach would allow a customizer function to be passed as the last argument so that the user can decide whether or not they want to retain the reference. That would be more consistent with `assign` behavior.  Does that sound okay?

**Comment by nikitaeverywhere** [comment]
For me "customizer function" sounds a bit strange... How will it work? If it would process each single property from the passed objects (and decide whether or not to clone it) this will slow down the initial implementation. And is the `assign` you mentioned corresponds to `Object.assign`?

It is hard to tell whether your library should do this by default. Yes, `Object.assign` mutates all property values, it's okay for your library to keep the same behavior. In this case, my issue just turns more to a kind of a question :)

**Comment by jonschlinkert** [comment]
Actually, after looking at this again, this shouldn't clone, it should only "assign".  I think both values in your example should be `true`, not `false`.

**Comment by nikitaeverywhere** [comment]
@jonschlinkert, my very base case is that as a user, I expected `assignDeep` to behave like `clone`. In other words, make a 100% clone of the object without mutating any of its properties. If that isn't true, that's okay, however, then I need another library for my case :) Feel free to close this issue.

**Comment by jonschlinkert** [comment]
got it, maybe take a look at https://github.com/jonschlinkert/merge-deep, perhaps that's closer to what you need.
