### ISSUE TITLE
cann't assign to an empty object

### ISSUE THREAD

**Issue by succeed2011** [jonschlinkert/assign-deep#8]
for example:

var assign = require('assign-deep');

var res1 = assign({}, {b: {c: 1}});

var res2 = Object.assign({}, {b: {c: 1}});
 
console.log(res1); //{}
console.log(res2); //{b:{c:1}}

is this a bug?

**Comment by jonschlinkert** [comment]
Can't reproduce.  This is what I get:

```js
var assign = require('assign-deep');
var res1 = assign({}, {b: {c: 1}});

var res2 = Object.assign({}, {b: {c: 1}});

console.log(res1); // { b: { c: 1 } }
console.log(res2); // { b: { c: 1 } }
```
