### ISSUE TITLE
Is there a way to stop it

### ISSUE THREAD

**Issue by iStryker** [jonschlinkert/assign-deep#9]
Practical application is a local configuration loading the default configuration if it is doesn't exist (if it is deeper).   In the local configuration, I was to stop it from loading the deeper default configuration.  Is this possible?

For example:
var local = a: { b: false };
var default = a: { b: { c: { d, e}}}, x: { y, z};
console.log(assign(local, default));

desire result is  a {b: false}, x: {y, z}

**Comment by doowb** [comment]
@iStryker you should change the order of your "configuration" objects:

```js
console.log(assign(default, local));
```

This will cause the `local` values to overwrite the `default` values.
